### ISSUE TITLE
improve TS phantom type example

### ISSUE THREAD

**Issue by JohnGurin** [TeyKey1/tey.sh#81]
https://github.com/TeyKey1/tey.sh/blob/fc8c80120a098145f4ed3a7a232936083e05ba2e/til-content/003_phantom_types_in_typescript.md?plain=1#L166

Since TS 5.0
```typescript
declare function analyticsEvent<const T>(event: Event<T>, payload: T): void

// @ts-expect-error
analyticsEvent(ANALYTICS_SHARE_EVENT, {method:"smth", url: 'dsf'}) 
```
`T` must be const param, otherwise `method` gets coerced to `string`.

**Comment by TeyKey1** [comment]
Great catch, and thanks for the info! I fixed the code accordingly and added an explanation.
